"""Deterministic historical-bar order simulation for Phase 6 backtests."""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from enum import StrEnum
from math import isfinite

from brooks_trader.models import Bar, Direction, Order, OrderStatus, OrderType, StrategySignal


class ExecutionEventType(StrEnum):
    """Observable broker events emitted while replaying one bar."""

    ENTRY_FILLED = "ENTRY_FILLED"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    TRADE_CLOSED = "TRADE_CLOSED"


@dataclass
class PendingEntry:
    """A stop-entry order that cannot trigger before its signal bar closes."""

    order: Order
    signal: StrategySignal
    quantity: float
    eligible_index: int
    expires_index: int


@dataclass
class OpenPosition:
    """Mutable intrabar state for one open position."""

    trade_id: str
    signal: StrategySignal
    quantity: float
    entry_index: int
    entry_time: datetime
    entry_price: float
    stop_price: float
    target_price: float | None
    mfe: float = 0.0
    mae: float = 0.0


@dataclass(frozen=True)
class ClosedTrade:
    """Execution result handed from the broker to the backtest engine."""

    trade_id: str
    signal: StrategySignal
    quantity: float
    entry_index: int
    entry_time: datetime
    entry_price: float
    stop_price: float
    target_price: float | None
    exit_index: int
    exit_time: datetime
    exit_price: float
    exit_reason: str
    mfe: float
    mae: float


@dataclass(frozen=True)
class ExecutionEvent:
    """One fill or cancellation generated by the historical broker."""

    event_type: ExecutionEventType
    bar_index: int
    order: Order
    fill_price: float | None = None
    trade: ClosedTrade | None = None


class PaperBroker:
    """A bar-based PaperBroker with explicit, conservative fill assumptions.

    The broker only accepts stop entries in Phase 6. Entry signals are submitted after
    the signal bar has closed and therefore become eligible on the following bar. A
    stop or target touched by the same bar is resolved according to
    ``same_bar_stop_target_policy``; ``adverse`` gives the stop priority.
    """

    def __init__(
        self,
        *,
        tick_size: float,
        slippage_ticks: int = 0,
        commission_per_trade: float = 0.0,
        same_bar_stop_target_policy: str = "adverse",
        pending_order_expiry_bars: int = 1,
    ) -> None:
        if not isfinite(tick_size) or tick_size <= 0:
            raise ValueError("tick_size must be finite and positive")
        if slippage_ticks < 0:
            raise ValueError("slippage_ticks cannot be negative")
        if not isfinite(commission_per_trade) or commission_per_trade < 0:
            raise ValueError("commission_per_trade must be finite and non-negative")
        if same_bar_stop_target_policy not in {"adverse", "favorable"}:
            raise ValueError("same_bar_stop_target_policy must be 'adverse' or 'favorable'")
        if pending_order_expiry_bars < 1:
            raise ValueError("pending_order_expiry_bars must be at least one")
        self.tick_size = tick_size
        self.slippage_ticks = slippage_ticks
        self.commission_per_trade = commission_per_trade
        self.same_bar_stop_target_policy = same_bar_stop_target_policy
        self.pending_order_expiry_bars = pending_order_expiry_bars
        self._order_counter = 0
        self._trade_counter = 0
        self._last_bar_index: int | None = None
        self._pending: PendingEntry | None = None
        self._position: OpenPosition | None = None
        self._order_states: dict[str, Order] = {}
        self._order_history: list[Order] = []

    @property
    def pending_entry(self) -> PendingEntry | None:
        return self._pending

    @property
    def position(self) -> OpenPosition | None:
        return self._position

    @property
    def orders(self) -> tuple[Order, ...]:
        """Return the latest state for each order in deterministic order."""
        return tuple(self._order_states.values())

    @property
    def order_history(self) -> tuple[Order, ...]:
        return tuple(self._order_history)

    def submit_signal(
        self,
        signal: StrategySignal,
        *,
        quantity: float,
        submitted_index: int,
    ) -> Order:
        """Submit a stop entry and make it eligible only from ``submitted_index + 1``."""
        if quantity <= 0 or not isfinite(quantity):
            raise ValueError("quantity must be finite and positive")
        order = Order(
            id=self._next_order_id(),
            timestamp=signal.created_at,
            direction=signal.direction,
            order_type=OrderType.STOP,
            quantity=quantity,
            price=signal.setup.entry,
        )
        if self._pending is not None or self._position is not None:
            order = order.model_copy(
                update={
                    "status": OrderStatus.REJECTED,
                    "rejection_reason": "existing_position_or_pending_entry",
                }
            )
            self._record_order(order)
            return order
        self._pending = PendingEntry(
            order=order,
            signal=signal,
            quantity=quantity,
            eligible_index=submitted_index + 1,
            expires_index=submitted_index + self.pending_order_expiry_bars,
        )
        self._record_order(order)
        return order

    def process_bar(self, bar: Bar, *, bar_index: int) -> list[ExecutionEvent]:
        """Process one bar, filling eligible entries and then managing the position."""
        if self._last_bar_index is not None and bar_index <= self._last_bar_index:
            raise ValueError("broker bar_index must increase strictly")
        self._last_bar_index = bar_index
        events: list[ExecutionEvent] = []
        entry_event = self._process_pending(bar, bar_index)
        entered_this_bar = entry_event is not None and (
            entry_event.event_type == ExecutionEventType.ENTRY_FILLED
        )
        if entry_event is not None:
            events.append(entry_event)
        if self._position is not None:
            self._update_excursion(bar)
            exit_event = self._process_exit(
                bar,
                bar_index,
                entered_this_bar=entered_this_bar,
            )
            if exit_event is not None:
                events.append(exit_event)
        return events

    def force_close(self, bar: Bar, *, bar_index: int) -> list[ExecutionEvent]:
        """Cancel pending entries and close an open position at the final close."""
        if self._last_bar_index is not None and bar_index < self._last_bar_index:
            raise ValueError("force-close bar cannot precede the latest processed bar")
        events: list[ExecutionEvent] = []
        if self._pending is not None:
            cancelled = self._pending.order.model_copy(
                update={
                    "status": OrderStatus.CANCELLED,
                    "rejection_reason": "END_OF_DATA",
                }
            )
            self._record_order(cancelled)
            self._pending = None
            events.append(
                ExecutionEvent(
                    event_type=ExecutionEventType.ORDER_CANCELLED,
                    bar_index=bar_index,
                    order=cancelled,
                )
            )
        if self._position is not None:
            self._update_excursion(bar)
            position = self._position
            fill_price = self._market_exit_price(position.signal.direction, bar.close)
            exit_order = self._filled_exit_order(position, bar, fill_price, "END_OF_DATA")
            closed = self._closed_trade(position, bar, bar_index, fill_price, "END_OF_DATA")
            self._position = None
            events.append(
                ExecutionEvent(
                    event_type=ExecutionEventType.TRADE_CLOSED,
                    bar_index=bar_index,
                    order=exit_order,
                    fill_price=fill_price,
                    trade=closed,
                )
            )
        return events

    def _process_pending(self, bar: Bar, bar_index: int) -> ExecutionEvent | None:
        pending = self._pending
        if pending is None or bar_index < pending.eligible_index:
            return None
        if bar_index > pending.expires_index:
            return self._cancel_pending(bar_index, "PENDING_ORDER_EXPIRED")
        trigger = pending.order.price
        if trigger is None:
            raise RuntimeError("pending stop order has no trigger price")
        triggered = (
            bar.high >= trigger
            if pending.signal.direction == Direction.LONG
            else bar.low <= trigger
        )
        if not triggered:
            if bar_index == pending.expires_index:
                return self._cancel_pending(bar_index, "PENDING_ORDER_EXPIRED")
            return None
        fill_price = self._entry_fill_price(pending.signal.direction, bar, trigger)
        filled = pending.order.model_copy(
            update={
                "status": OrderStatus.FILLED,
                "filled_at": bar.timestamp,
                "filled_price": fill_price,
            }
        )
        self._record_order(filled)
        self._pending = None
        signal = pending.signal
        setup = signal.setup
        self._position = OpenPosition(
            trade_id=self._next_trade_id(),
            signal=signal,
            quantity=pending.quantity,
            entry_index=bar_index,
            entry_time=bar.timestamp,
            entry_price=fill_price,
            stop_price=setup.initial_stop,
            target_price=setup.target,
        )
        return ExecutionEvent(
            event_type=ExecutionEventType.ENTRY_FILLED,
            bar_index=bar_index,
            order=filled,
            fill_price=fill_price,
        )

    def _process_exit(
        self,
        bar: Bar,
        bar_index: int,
        *,
        entered_this_bar: bool,
    ) -> ExecutionEvent | None:
        position = self._position
        if position is None:
            return None
        if entered_this_bar and self._entry_open_is_beyond_target(position, bar):
            reason = "TARGET"
            fill_price = self._market_exit_price(position.signal.direction, bar.open)
            exit_order = self._filled_exit_order(position, bar, fill_price, reason)
            closed = self._closed_trade(position, bar, bar_index, fill_price, reason)
            self._position = None
            return ExecutionEvent(
                event_type=ExecutionEventType.TRADE_CLOSED,
                bar_index=bar_index,
                order=exit_order,
                fill_price=fill_price,
                trade=closed,
            )
        open_reason = None if entered_this_bar else self._open_exit_reason(position, bar)
        stop_hit, target_hit = self._exit_hits(position, bar)
        if open_reason is not None:
            reason = open_reason
        elif not stop_hit and not target_hit:
            return None
        elif stop_hit and target_hit:
            reason = "STOP_LOSS" if self.same_bar_stop_target_policy == "adverse" else "TARGET"
        else:
            reason = "STOP_LOSS" if stop_hit else "TARGET"
        reference = position.stop_price if reason == "STOP_LOSS" else position.target_price
        if reference is None:
            raise RuntimeError("target exit selected without a target")
        fill_price = self._exit_fill_price(
            position.signal.direction,
            bar,
            reference,
            reason,
            allow_open_gap=not entered_this_bar,
        )
        exit_order = self._filled_exit_order(position, bar, fill_price, reason)
        closed = self._closed_trade(position, bar, bar_index, fill_price, reason)
        self._position = None
        return ExecutionEvent(
            event_type=ExecutionEventType.TRADE_CLOSED,
            bar_index=bar_index,
            order=exit_order,
            fill_price=fill_price,
            trade=closed,
        )

    def _entry_open_is_beyond_target(self, position: OpenPosition, bar: Bar) -> bool:
        """Detect an immediately marketable bracket target after a gap entry."""
        if position.target_price is None:
            return False
        if position.signal.direction == Direction.LONG:
            return bar.open >= position.target_price
        return bar.open <= position.target_price

    def _open_exit_reason(self, position: OpenPosition, bar: Bar) -> str | None:
        """Resolve gaps at the known-first open before ambiguous intrabar extremes."""
        if position.signal.direction == Direction.LONG:
            if bar.open <= position.stop_price:
                return "STOP_LOSS"
            if position.target_price is not None and bar.open >= position.target_price:
                return "TARGET"
        else:
            if bar.open >= position.stop_price:
                return "STOP_LOSS"
            if position.target_price is not None and bar.open <= position.target_price:
                return "TARGET"
        return None

    def _exit_hits(self, position: OpenPosition, bar: Bar) -> tuple[bool, bool]:
        if position.signal.direction == Direction.LONG:
            stop_hit = bar.open <= position.stop_price or bar.low <= position.stop_price
            target_hit = position.target_price is not None and (
                bar.open >= position.target_price or bar.high >= position.target_price
            )
        else:
            stop_hit = bar.open >= position.stop_price or bar.high >= position.stop_price
            target_hit = position.target_price is not None and (
                bar.open <= position.target_price or bar.low <= position.target_price
            )
        return stop_hit, target_hit

    def _update_excursion(self, bar: Bar) -> None:
        position = self._position
        if position is None:
            return
        if position.signal.direction == Direction.LONG:
            position.mfe = max(position.mfe, bar.high - position.entry_price)
            position.mae = max(position.mae, position.entry_price - bar.low)
        else:
            position.mfe = max(position.mfe, position.entry_price - bar.low)
            position.mae = max(position.mae, bar.high - position.entry_price)
        position.mfe = max(0.0, position.mfe)
        position.mae = max(0.0, position.mae)

    def _entry_fill_price(self, direction: Direction, bar: Bar, trigger: float) -> float:
        slippage = self.slippage_ticks * self.tick_size
        if direction == Direction.LONG:
            base = bar.open if bar.open >= trigger else trigger
            return base + slippage
        base = bar.open if bar.open <= trigger else trigger
        return base - slippage

    def _exit_fill_price(
        self,
        direction: Direction,
        bar: Bar,
        reference: float,
        reason: str,
        *,
        allow_open_gap: bool,
    ) -> float:
        slippage = self.slippage_ticks * self.tick_size
        if direction == Direction.LONG:
            if reason == "STOP_LOSS":
                base = (
                    min(bar.open, reference)
                    if allow_open_gap and bar.open <= reference
                    else reference
                )
            else:
                base = (
                    max(bar.open, reference)
                    if allow_open_gap and bar.open >= reference
                    else reference
                )
            return base - slippage
        if reason == "STOP_LOSS":
            base = (
                max(bar.open, reference) if allow_open_gap and bar.open >= reference else reference
            )
        else:
            base = (
                min(bar.open, reference) if allow_open_gap and bar.open <= reference else reference
            )
        return base + slippage

    def _market_exit_price(self, direction: Direction, reference: float) -> float:
        slippage = self.slippage_ticks * self.tick_size
        return reference - slippage if direction == Direction.LONG else reference + slippage

    def _filled_exit_order(
        self,
        position: OpenPosition,
        bar: Bar,
        fill_price: float,
        reason: str,
    ) -> Order:
        if reason == "STOP_LOSS":
            order_type = OrderType.STOP
        elif reason == "TARGET":
            order_type = OrderType.LIMIT
        else:
            order_type = OrderType.MARKET
        order = Order(
            id=self._next_order_id(),
            timestamp=bar.timestamp,
            direction=position.signal.direction,
            order_type=order_type,
            quantity=position.quantity,
            price=(
                position.stop_price
                if reason == "STOP_LOSS"
                else position.target_price if reason == "TARGET" else None
            ),
            status=OrderStatus.FILLED,
            filled_at=bar.timestamp,
            filled_price=fill_price,
        )
        self._record_order(order)
        return order

    def _closed_trade(
        self,
        position: OpenPosition,
        bar: Bar,
        bar_index: int,
        exit_price: float,
        exit_reason: str,
    ) -> ClosedTrade:
        return ClosedTrade(
            trade_id=position.trade_id,
            signal=position.signal,
            quantity=position.quantity,
            entry_index=position.entry_index,
            entry_time=position.entry_time,
            entry_price=position.entry_price,
            stop_price=position.stop_price,
            target_price=position.target_price,
            exit_index=bar_index,
            exit_time=bar.timestamp,
            exit_price=exit_price,
            exit_reason=exit_reason,
            mfe=position.mfe,
            mae=position.mae,
        )

    def _cancel_pending(self, bar_index: int, reason: str) -> ExecutionEvent:
        pending = self._pending
        if pending is None:
            raise RuntimeError("no pending order to cancel")
        cancelled = pending.order.model_copy(
            update={"status": OrderStatus.CANCELLED, "rejection_reason": reason}
        )
        self._record_order(cancelled)
        self._pending = None
        return ExecutionEvent(
            event_type=ExecutionEventType.ORDER_CANCELLED,
            bar_index=bar_index,
            order=cancelled,
        )

    def _record_order(self, order: Order) -> None:
        self._order_states[order.id] = order
        self._order_history.append(order)

    def _next_order_id(self) -> str:
        self._order_counter += 1
        return f"order-{self._order_counter:06d}"

    def _next_trade_id(self) -> str:
        self._trade_counter += 1
        return f"trade-{self._trade_counter:06d}"
